export const GENRE_MAP: Record<string, string> = {
  thriller: "триллер",
  drama: "драма",
  comedy: "комедия",
  action: "боевик",
  horror: "ужасы",
  crime: "криминал",
  adventure: "приключения",
  fantasy: "фэнтези",
  romance: "роман",
  scifi: "научная фантастика",
  mystery: "мистика",
  family: "семейный",
  tvmovie: "телевизионный фильм",
  war: "военный",
  history: "исторический",
  documentary: "документальный",
  western: "вестерн",
  standup: "стендап",
};
